### ISSUE TITLE
Do we need `OverloadedStrings`?

### ISSUE THREAD

**Issue by ecaustin** [ku-fpg/hermit-shell#11]
We have had to back off overloading commands on the client side because `OverloadedStrings` is causing too many type ambiguities to make it worthwhile, e.g. is `unfold (["foo", "bar"] :: [OccurrenceName])` really preferable to `unfoldAny ["foo", "bar"]).

Do we need `OverloadedStrings` though?

We don't have a tab completion engine anymore so distinguishing between `OccurrenceName`, `HermitName`, etc. is unnecessary.

We could instead convert those arguments to `String` values and do the parsing server side (This is what I've done with a few commands already, e.g. `unfold` and `inline`.).

Another bonus of this approach is that we don't have to worry about how to serialize `HermitName`s with `aeson` since we can just send simple `String` values.

**Comment by andygill** [comment]
I've added a [wiki page](../wiki/Variadic-Functions-in-Shell-DSL), where can discuss variadic tradeoffs, including Overloading strings.

**Comment by andygill** [comment]
The question is open, though. Do we need Overloaded Strings? We can examine our DSL to see.

The overloading allows slightly better typing for `Name`, but does force non-overloaded String-style arguments (or add types, which we want to avoid).

**Comment by ecaustin** [comment]
I believe Ryan took care of this issue when he redid most of the API.
