### ISSUE TITLE
Issues with wwSplit and wwSplitUnsafe

### ISSUE THREAD

**Issue by roboguy13** [ku-fpg/hermit-shell#14]
I'm trying to remove all the `eval`s in `examples/fib-tuple` and I'm running into an issue that I narrowed down to the line `eval "ww-split [| wrap |] [| unwrap |] (ww-AssA-to-AssC WWA)"`. It works fine in `eval`, but if I use `apply $ wwSplit "wrap" "unwrap" (wwAssAToAssC wwa)`, it gives the following error

    Rewrite failed:worker/wrapper factorisation failed: abs/rep types do not match fix body type.

I've also tried using `wwSplitUnsafe "wrap" "unwrap"`, which gives the same error. This works fine though

    eval "ww-split-unsafe [| wrap |] [| unwrap |]"

I also noticed that the `CoreString`s include the leading and trailing space, but putting those in doesn't solve the issue either.

**Comment by ecaustin** [comment]
This is possibly related to the concern I raised when we first talked about quasi-quoting where I mentioned that strings may parse to different expressions in the client and server.

The first step in debugging this would be to evaluate `parseCoreExprT "wrap" &&& parseCoreExprT "unwrap"` on the server and client both and compare their outputs to confirm my suspicions.

If that doesn't immediately show that something's wrong, then we'll probably have to trace through the definition of wwSplit to see when things go haywire.  I'll be in later today to help with this.

**Comment by andygill** [comment]
I'd suggest seeing if we can leveraging the TH parser.

**Comment by ecaustin** [comment]
Uhh, something else unrelated to the parser may be screwing things up.

If I load the Fib.hs file from this examples directory with hermit-shell, I only see three bindings:  `fib` and two versions of `main`.

If I load the same file with hermit, though, all of the bindings are in scope; including `wrap` and `unwrap`.

Anyone else having this issue, or just me?

**Comment by roboguy13** [comment]
@ecaustin I see `wrap` and `unwrap` with both hermit and hermit-shell. Are you sure you're in `examples/fib-tuple` and not `examples/fib`?

By the way, I've successfully converted other examples using the `[| ... |]` style syntax so I'm not sure if the issue is with the parsing  (for example, `examples/concatVanishes/RevScript.hs`). I think those were represented as `String`s though, and this is represented as a `CoreString`. Maybe if we change `CoreString` to `String` on the client-side, it will fix the issue.

**Comment by ecaustin** [comment]
I'm wondering if this is potentially a GHC 7.10 bug, but I can't get hermit-shell to build with GHC 7.8 to test it (missing Typeable instances).

Well currently we transmit the arguments for `wwSplit` as `String`s, but we parse them as `CoreString`s.
I didn't think there would be an issue since the `parseExternal` method for `CoreString` expects a `String` aeson `Value`, but maybe transmitting `CoreString`s just to be safe would be a good idea.  It would probably require adding a `ToJSON` instance for `CoreString`.

**Comment by ecaustin** [comment]
Nope, I'm still only seeing `fib` and `main` as bindings with GHC 7.8 and 7.10.  I'll open a separate issue after I test to see if this is an OS X specific issue or not.

**Comment by ecaustin** [comment]
I have hermit-shell working as intended now, so I cleaned up the comment thread a bit to remove that discussion.

As of right now we know that worker-wrapper rewrites work fine when triggered by `wwResultSplitStaticArg` but not `wwSplit`.

This would seem to indicate that the issues are unrelated to parsing expressions.

I have no idea how much of a code base these two methods share past that, but I'll look into it tomorrow to see what's going wrong.

**Comment by ecaustin** [comment]
I'm embarrassed by how long this took me to figure out...

WorkerWrapper/Fix.hs and WorkerWrapper/FixResult.hs both contain a definition for `wwSplit`.  Whoever did the original translation of the external values exposed the wrong one.

Commit https://github.com/ku-fpg/hermit/commit/fa4bc8cbaa1a31e50391a86f4aec77d00c817d59 fixes the problem and commit https://github.com/ku-fpg/hermit-shell/commit/7af279a9cd0b345058cb95fe0c2c151957660aab fixes the `fib-tuple` test to remove the use of `eval`.

**Comment by roboguy13** [comment]
@ecaustin Confusingly, we actually need both `wwSplit`s. This change seems to have broken `wwResultSplit` in hermit-shell. I'll rename the `wwSplit` that is associated with the `wwResultSplit` hermit command to `wwResultSplit`.
