### ISSUE TITLE
Add diff checking to tests

### ISSUE THREAD

**Issue by roboguy13** [ku-fpg/hermit-shell#19]
Eventually, we should run both hermit and hermit-shell on all the tests and automatically verify that the diff of the outputs. Once this is done, the workaround in 1dd94f3f can be removed.

**Comment by RyanGlScott** [comment]
This should be fixed now. I decided to keep the "workaround" in 1dd94f3fec91dfcc3a52a246a38aee91b4f44d4b, though, since it proves to be very useful for aborting on a malformed script before running the full test, since each test takes a good 3-8 seconds.
