### ISSUE TITLE
Run QueryFun

### ISSUE THREAD

**Issue by xich** [ku-fpg/hermit-shell#22]
```
HERMIT> run log

<interactive>:23:1:
    No instance for (Run QueryFun) arising from a use of ‘run’
    In the expression: run
    In the expression: run log
    In an equation for ‘it’: it = run log
```

Similiar problem for `run $ diff 1 2`... is there a way to run `QueryFun`s?

**Comment by roboguy13** [comment]
I just added that in f5042fa. It should work with `run`, a dedicated `queryFun :: QueryFun -> Shell ()` function and also when directly typed at the REPL.
