### ISSUE TITLE
Add deriving instance for KURE and HERMIT

### ISSUE THREAD

**Issue by andygill** [ku-fpg/hermit-shell#6]
Add deriving instance, as needed, to KURE and HERMIT, making the build 7.10 compatible.

Right now, we have a list of deriving instance in module HERMIT.Server.Parser.Utils. They can all be moved to KURE and HERMIT.

**Comment by RyanGlScott** [comment]
Fixed in 9c2d3bff6d0cc849969c139ff3e39c843c1f70cc.
