### ISSUE TITLE
Better Ctrl+C handling

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit-shell#8]
Right now, pressing `Ctrl+C` twice from `hermit-shell` will exit the interactive shell, but not the `scotty` server, leading to all sorts of wackiness.

**Comment by ecaustin** [comment]
This is fixed by https://github.com/ku-fpg/hermit-shell/issues/9 if you do `Ctrl+D` once instead of `Ctrl+C` twice.
